### ISSUE TITLE
yy ecosystem failed under sanitizer

### ISSUE THREAD

**Issue by tankf33der** [chaos-lang/chaos#11]
**Describe the bug**
crash

**To Reproduce**
recompile with clang and -fsanitize=memory
```
$ cd tests
$ ../chaos array.kaos
==17859==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55b41daea040 in yy_get_next_buffer /home/mpech/chaos/lex.yy.c:1349:7
    #1 0x55b41dae6ea5 in yylex /home/mpech/chaos/lex.yy.c:1183:17
    #2 0x55b41dad3869 in yyparse /home/mpech/chaos/chaos.tab.c:1677:16
    #3 0x55b41dae0d3b in main /home/mpech/chaos/chaos.y:470:9
    #4 0x7f16414c5152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
    #5 0x55b41da5723d in _start (/home/mpech/chaos/chaos+0x2023d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/mpech/chaos/lex.yy.c:1349:7 in yy_get_next_buffer
Exiting
```

**Environment:**
 - CPU Architecture: x86_64
 - Operating System - Distro : Manjaro Linux
 - C Compiler Name and Version: clang 9.0.1
 - Chaos Language Version: latest master

**Comment by mertyildiran** [comment]
@tankf33der this issue is no longer exists as of https://github.com/chaos-lang/chaos/commit/60a48a544ad2cedb7490f9f9cceb050089975eca and it's guaranteed to be never happen again by [a MemorySanitizer test](https://github.com/chaos-lang/chaos/runs/540929541).
