### ISSUE TITLE
fix undefined sanitizer warning

### ISSUE THREAD

**Issue by tankf33der** [chaos-lang/chaos#15]
latest master. clang. x64. add -fsanitize=undefined to clang call.
```
$ make clang
$ cd tests
$ ./run.sh
<SKIP>
Running test: symbol_table
OK
Running test: function
functions/function.c:43:9: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:43:28: note: nonnull attribute specified here
OK
Running test: boolean
OK
</SKIP
```

**Comment by mertyildiran** [comment]
@tankf33der this issue is no longer exists as of https://github.com/chaos-lang/chaos/commit/b843cd15d4cdbfcf7eec76da267bfc9622f57433 and it's guaranteed to be never happen again by [an UndefinedBehaviorSanitizer test](https://github.com/chaos-lang/chaos/runs/540998378).
