### ISSUE TITLE
[Bug] print numbers inside times loop

### ISSUE THREAD

**Issue by tankf33der** [chaos-lang/chaos#20]
print inside times loop dont respect and prints immediately.

Example code below:

```
### 3 times do
... print "mike"
... end
mike
mike
mike
### 3 times do
... print 0
0
... end
0
0
0
```

**Comment by mertyildiran** [comment]
@tankf33der fixed with https://github.com/chaos-lang/chaos/commit/0cef2cb5949fe23da0fa77a38adbe0a5caed8769
