### ISSUE TITLE
Implement loops with a syntax similar to Ruby and PHP/Python

### ISSUE THREAD

**Issue by mertyildiran** [chaos-lang/chaos#4]
Implement loops like it's being done in Ruby:

```ruby
3.times do
    # do work here
end 
```

and PHP:

```php
foreach ($arr as $value) {
    # do work here
}
```

or Python:

```python
for x in list:
    # do work here
```

We don't need to implement `while`. The main requirement here is:
 - Loops should not contain any boolean expression.

The reason behind this requirement is to prevent the occurrence of any infinite loops. If an infinite loop is really necessary then there will be `INFINITE` keyword to achieve that.

#### Ruby Style

```
num a = 5
T_INT times do:
    print a
```

#### PHP/Python Style

```
num a = 5
foreach T_VAR in T_VAR:
    print a
```

Code block indicator will be `\t` <kbd>TAB</kbd> character only, opposed to Python's *"8 spaces but maybe tabs too"*.

**Comment by mertyildiran** [comment]
Implemented with https://github.com/chaos-lang/chaos/commit/422c59250b64b86acac5333384dd8d11e0158192

**Comment by Nokiand** [comment]
Code block requirement is also like the new language ERG (ml, ocaml, type inference) on gitHub; 3 but 8 whitesapaces, tabs must converted.  Multi-statement lines or else, what about code seen in compact environments?  Python with EOL delimiters looks like D digMars.
