### ISSUE TITLE
[Bug] Chaos crashes if function redefined a lot of times.

### ISSUE THREAD

**Issue by lewek** [chaos-lang/chaos#57]
**Describe the bug**
Chaos crashes if function redefined a lot of times.

**To Reproduce**
```
bash-3.2$ ./chaos
    Chaos Language 0.0.1-alpha (Aug 11 2020 17:01:34)      
    Clang version: 7.0.2 on osx                            
    Turn chaos into magic!                                 

kaos> void def hello()
....  end
kaos> void def hello()
....  end
kaos> void def hello()
chaos(14134,0x7fff8b81c380) malloc: *** error for object 0x10e45824a: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Expected behavior**
Anything, but not a crash.

**Screenshots**
```
bash-3.2$ ./chaos
    Chaos Language 0.0.1-alpha (Aug 11 2020 17:01:34)      
    Clang version: 7.0.2 on osx                            
    Turn chaos into magic!                                 

kaos> void def hello()
....  end
kaos> void def hello()
....  end
kaos> void def hello()
chaos(14134,0x7fff8b81c380) malloc: *** error for object 0x10e45824a: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Environment:**
 - CPU Architecture: i386
 - Operating System - Distro: MacOS 10.13.6
 - C Compiler Name and Version: clang 7.0.2
 - Chaos Language Version: 0.0.1-alpha (latest)

**Comment by mertyildiran** [comment]
@lewek the crash is not present in [`feature/ast`](https://github.com/chaos-lang/chaos/tree/feature/ast) which I'm going to merge it to `master` soon. Though we should either throw an error when the `hello()` function is redefined or just update the function.

Here are the tests that I've done manually, just now in [the current state of `feature/ast` branch](https://github.com/chaos-lang/chaos/commit/13551e878bd3c0c1fc884a152bd5938ce473f930):

```chaos
kaos> void def hello()
....      print 1
....  end
kaos> void def hello()
....      print 2
....  end
kaos> void def hello()
....      print 3
....  end
kaos> hello()
1
kaos> function_table
[start] =>
	{name: hello, type: 6, parameter_count: 0, optional_parameter_count: 0, decision_length: 0, context: /home/mertyildiran/Documents/chaos/__interactive__.kaos, module_context: /home/mertyildiran/Documents/chaos/__interactive__.kaos, module: } =>
	{name: hello, type: 6, parameter_count: 0, optional_parameter_count: 0, decision_length: 0, context: /home/mertyildiran/Documents/chaos/__interactive__.kaos, module_context: /home/mertyildiran/Documents/chaos/__interactive__.kaos, module: } =>
	{name: hello, type: 6, parameter_count: 0, optional_parameter_count: 0, decision_length: 0, context: /home/mertyildiran/Documents/chaos/__interactive__.kaos, module_context: /home/mertyildiran/Documents/chaos/__interactive__.kaos, module: } =>
[end]
```

Let's take a look at this issue after I've merged the `feature/ast` branch.

**Comment by mertyildiran** [comment]
@lewek OK I've studied the problem and came up with a solution. Since the function parsing logic can parse the functions multiple times because of the circular module imports, we are going to just overwrite the function instead of throwing an error on function redefinition.

Just like [the function here](https://github.com/chaos-lang/chaos/blob/fb30b8e9c17a0ab054c9bdb4998bc37d5e0568c9/symbol.c#L102-L125) to remove the variables, we need to add this function to **`functions/function.c`** to be able to remove Chaos functions:

```c
void removeFunction(_Function* function) {
    _Function* previous_function = function->previous;
    _Function* next_function = function->next;

    if (previous_function == NULL && next_function == NULL) {
        start_function = NULL;
        end_function = NULL;
        freeFunction(function);
        return;
    } else if (previous_function == NULL) {
        start_function = next_function;
        start_function->previous = NULL;
    } else if (next_function == NULL) {
        end_function = previous_function;
        end_function->next = NULL;
    } else {
        previous_function->next = next_function;
        next_function->previous = previous_function;
    }

    freeFunction(function);
}
```

Then we need to add another function to **`functions/function.c`** to detect if the function is already defined and remove it:

```c
void removeFunctionIfDefined(char *name) {
    unsigned short parent_context = 1;
    if (module_path_stack.size > 1) parent_context = 2;

    function_cursor = start_function;
    while (function_cursor != NULL) {
        if (strcmp(function_cursor->name, name) == 0 &&
            strcmp(function_cursor->context, module_path_stack.arr[module_path_stack.size - parent_context]) == 0 &&
            strcmp(function_cursor->module_context, module_path_stack.arr[module_path_stack.size - 1]) == 0 &&
            strcmp(function_cursor->module, module_stack.arr[module_stack.size - 1]) == 0
        ) {
            _Function* function = function_cursor;
            removeFunction(function);
            return;
        }
        function_cursor = function_cursor->next;
    }
}
```

Lastly, we need to call this function before populating `function_mode` (`struct _Function`); like `removeFunctionIfDefined(name);` in **[here](https://github.com/chaos-lang/chaos/blob/fb30b8e9c17a0ab054c9bdb4998bc37d5e0568c9/functions/function.c#L22-L23)**.

It would be good to add a simple test like this to guarantee that this will never happen again:

**`tests/function_redefinition.kaos`**:

```chaos
void def hello()
    print 1
end

void def hello()
    print 2
end

void def hello()
    print 3
end

hello()
```

**`tests/function_redefinition.out`**:

```
3
```

@lewek would you like to do these changes and send a pull request?

**Comment by mertyildiran** [comment]
@lewek since you haven't responded, I'm going to do these changes then.

**Comment by mertyildiran** [comment]
@lewek fixed with https://github.com/chaos-lang/chaos/commit/6b5c81fce085a9c9178116509f4ac7eaf19f5e62
