### ISSUE TITLE
What is the default path for kaos modules (Linux/Windows)?

### ISSUE THREAD

**Issue by lewek** [chaos-lang/chaos#58]
@mertyildiran @melihs 

What is the default path for kaos modules (Linux/Windows)?

**Comment by mertyildiran** [comment]
@lewek Chaos modules are located under `spells/` directory in the project root as it's mentioned in [here](https://chaos-lang.org/docs/17_spells). The modules are installed by `occultist` are not system-wide but rather project-wide. By "**project root**" I mean the directory that you have run `occultist install blabla`.

If you are actually asking about the location of C headers for developing Chaos C extensions then the location of the header files can be found under [here](https://github.com/chaos-lang/chaos/blob/e8759514f6ed11815a2f265c752dfa7fc3f6e094/Makefile#L15-L19) (for Linux and macOS) and [here](https://github.com/chaos-lang/chaos/blob/e8759514f6ed11815a2f265c752dfa7fc3f6e094/make.bat#L130-L145) (for Windows).

**Comment by lewek** [comment]
@mertyildiran @melihs Also I can’t find information about reading user input in Chaos. I read I/O docs but found only output functions like `echo` and `print`.
Is there any way to read user input in Chaos?

**Comment by mertyildiran** [comment]
@mertyildiran reading user input is not yet implemented. Just like [your questions about executing system commands](https://github.com/chaos-lang/chaos/issues/55) it will be implemented in an official Chaos spell (a Chaos C extensions) named `io` which I did haven't created yet.

If you're willing to develop these core modules (like [math](https://github.com/chaos-lang/math)) then I can invite you to the organization and you can create those Chaos C extensions. Would you like to join?

**Comment by mertyildiran** [comment]
@lewek since the question is answered, I'm closing it.
