### ISSUE TITLE
[Bug] REPL not starting properly after building in MSYS2 on Win10

### ISSUE THREAD

**Issue by arabelladonna** [chaos-lang/chaos#76]
**Describe the bug**
The REPL is not starting properly when built in MSYS2. Other functions may not work properly, but I haven't attempted to test them, as the REPL does not start.

Here is what I see when I attempt to run the tests listed in the README:

```
ari@DESKTOP-1ER5E33 MINGW64 ~/chaos
$ chaos
print "hello world"
```

Note that there's no version information or `print` output.

**To Reproduce**
1. Follow the install instructions in the README in MSYS2: `make requirements`, `make`, `make install`.
2. Run the `chaos` binary.

**Expected behavior**
The REPL to start, starting with listing version information.

**Environment:**
 - CPU Architecture: x86_64, mingw64 MSYS2 terminal
 - Operating System - Distro : Windows 10
 - C Compiler Name and Version: gcc 9.3.0 (Rev1, Built by MSYS2 project
 - Chaos Language Version: 0.1.0 (current repo version)

**Comment by mertyildiran** [comment]
@arabelladonna we do not support MSYS2 shell but rather we build native Windows programs using Mingw-w64. You should rather use `cmd` or Powershell to call `chaos`. Chaos language is not POSIX-compliant on Windows.

Please confirm that whether it works under `cmd` or Powershell on your machine or not.

**Comment by mertyildiran** [comment]
By the way [this is a really good answer](https://sourceforge.net/p/msys2/discussion/general/thread/dcf8f4d3/#8473/588e) that explains the MSYS2 vs. MINGW and the MSYS2 shell.

**Comment by arabelladonna** [comment]
The executable built in the MSYS2 mingw64 shell does, in fact, run properly in the command prompt.
