### ISSUE TITLE
[Bug] String literals cannot have parenthesis in them

### ISSUE THREAD

**Issue by zethra** [chaos-lang/chaos#77]
**Describe the bug**
String literals cannot have parenthesis in them.

**To Reproduce**
Declare a string literal with parenthesis in it
```kaos
koas> str test = "()"

  Syntax error:
    Module: /home/zethra/Projects/Personal/chaos-regex/__interactive__.kaos
    Line: 7
    Cause: "\n\n\nprint test\ntest = "
```

**Expected behavior**
I get a string

**Environment:**
 - CPU Architecture: `x86_64`
 - Operating System - Distro : Manjaro
 - C Compiler Name and Version: clang 11.0.0
 - Chaos Language Version: 0.1.0

**Comment by mertyildiran** [comment]
@zethra the issue fixed with:
- https://github.com/chaos-lang/chaos/commit/ace9255d2e20a24fde2c6f7d91cf2b95cdb709dd
- https://github.com/chaos-lang/chaos/commit/0f2b9a6f644f56071c616a2590af2ddd3a96d0d1
