### ISSUE TITLE
[Bug] Escape sequences not respected in echo/print of String literals in REPL

### ISSUE THREAD

**Issue by naltun** [chaos-lang/chaos#79]
**Describe the bug**
**echo** and **print** do not respect escape sequences in **String** literals.

**To Reproduce**
1. Start the REPL
2. Call **echo** or **print** with a string literal

**Expected behavior**
The escape sequences should be respected.

**Screenshots**
<img width="397" alt="image" src="https://user-images.githubusercontent.com/7507990/101106762-d2a3ff00-359e-11eb-94f1-b729244ab1dc.png">

**Environment:**
 - CPU Architecture: **x86_64**
 - Operating System - Distro : Arch Linux (rolling release-based distro)
 - C Compiler Name and Version **gcc 10.2.0**
 - Chaos Language Version **0.1.0 (Dec 3)** 

**Additional context**
This _is_ a REPL bug.

Here is a small program to demonstrate how this is not a bug when compiling:

```shell
/tmp $ cat hello.kaos
str a = "Hello\n\tWorld!"

echo a
print a

echo "Hello\n\tWorld!"
print "Hello\n\tWorld!"
/tmp $ ./build/hello
Hello
        World!Hello
        World!
Hello
        World!Hello
        World!
```

**Comment by mertyildiran** [comment]
@naltun it was actually not only a REPL bug but an interpreter bug in general. I've fixed it with https://github.com/chaos-lang/chaos/commit/8dc78d0e2fe030c89e2be1689cd54c3a27deb674
