### ISSUE TITLE
[RFC] Print Function Call Stack Trace

### ISSUE THREAD

**Issue by mertyildiran** [chaos-lang/chaos#94]
Print function call stack trace in case of an error. Consider the below example:

```ruby
num def f8()
    num z = 999
    return z
end

num def f7()
    num z = 42
    print not_existing_var
    return z
end

num def f6(num b)
    num y = b - 1
end {
    y > 1  : return y,
    y == 1 : f7()
}

num def f5(num a)
    num y = a - 1
end {
    y > 3  : f8(),
    y == 3 : f6(y),
    y == 2 : f6(y)
}

print f5(3)
```

Right now it's printing:

```shell
$ chaos dev.kaos
  Chaos Error:                               
    Module: dev.kaos                         
    Line: 8                                  
    Undefined variable: not_existing_var 
```

But it should instead print:

```shell
$ chaos dev.kaos
  Traceback (most recent call last):
    File: "dev.kaos", line 27, in <module>
      print f5(3)
    File: "dev.kaos", line 24, in f5
      y == 2 : f6(y)
    File: "dev.kaos", line 16, in f6
      y == 1 : f7()
    File: "dev.kaos", line 8, in f7
      print not_existing_var
  UndefinedVariable: not_existing_var
```

**Comment by naltun** [comment]
I work with Python a lot, and the stacktraces are helpful. I say let's get this in.

I'm not sure how to implement stacktracing, but I'd be happy to help out in research. If you have any ideas on how to proceed, let me know.

**Comment by mertyildiran** [comment]
@naltun I've turned the description into the exact Python traceback output format.

We build and print the current error message in [this function](https://github.com/chaos-lang/chaos/blob/d99eefc55639c2885a609e66d735eb3bfde5765c/interpreter/errors.c#L36). We'll simply walk through the [`function_call_stack`](https://github.com/chaos-lang/chaos/blob/d99eefc55639c2885a609e66d735eb3bfde5765c/interpreter/function.h#L84) and access the information like function name, the module and line number. Here is a draft that you can start with:

```c
char* function_name;
char* module_context;
int line_no;

for (unsigned i = 0; i < function_call_stack.size; i++) {
    function_name = function_call_stack.arr[i]->function->name;
    module_context = function_call_stack.arr[i]->function->module_context;
    line_no = function_call_stack.arr[i]->function->line_no;

    // Print `File: "<module_context>", line <line_no>, in <function_name>`
    // `FILE* fp fopen(module_context);`
    // Retrieve the line using `fp` and `line_no` and assign it to a char*
    // Print that line with additional indentation
}
```

Feel free to assign this task to yourself if you would like to do it.

**Comment by mertyildiran** [comment]
This feature is fully implemented with:

- 217c13d652751487574f149195c38732c82fe7a2
- 5fb8c2ffde251a248413a5ddcc8de46eb9f581d3
- cda36f8a71eb5277021cb81250d5ef0561b19a0c
- 6804e49250f257a30a102b682dd5d2fdedcd3880
- d8bb35aec31753eaab7e8765083386cd882e0ca6
- a5836f56b84dfc9d1f884038e80f6060db5fbcb3
- 505cf88f14241d60bcca132e9e07b678f32aadc1
- 0d59c28062305cb992a2b044b0cf1ed83a10e7c5
- b26d19736708c2f82cad38fb53acb72857fcef8c
- 7200361d07782fbf04097dcb7ff45a382fb22473
- 79bd3abc40deff1199af61e9dccbbb16cbb90d75
- 2ba257888c7aa247d1dbde4f4d054707abb95716
- 5b955a097b8c59741785dd3921bef6165b197323
